### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by XhmikosR** [phillipj/metalsmith-yearly-pagination#6]
Not sure which tools/rules to follow, but the repo needs linting so that we are consistent.

**Comment by phillipj** [comment]
In my point of view, linting for syntactically issues and obvious error prone code is what's important for now. I've personally had good experience with [`eslint:recommended`](https://eslint.org/docs/rules/) to handle that part.

As for formatting and consistent code style, this project has been stale for 4 years and I'd be extremely surprised if a flood of collaborators suddenly show up now. With that in mind, I'm not too worried about problematic inconsistencies. If it ever gets to that point, [prettier](https://prettier.io/) should decide to avoid any bikeshedding.

**Comment by XhmikosR** [comment]
This sounds a good starting point so I'm gonna make a PR tomorrow. Better
than nothing, for sure.

**Comment by XhmikosR** [comment]
Btw do you want to keep supporting Node.js 6.x?

**Comment by phillipj** [comment]
It's not very important for me to keep Node.js 6 support, no.
